services:
  db:
    image: postgres:15
    container_name: postgres_demo
    environment:
      - POSTGRES_DB=postgres_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data: